name: Update Hugging Face Datasets

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    
    # 🔑 Add this permissions block
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts/update_hf_datasets.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/huggingface_datasets.json
          git commit -m "Update Hugging Face datasets (auto)"
          git push
        continue-on-error: true
